version: '3'

networks:
  redpanda_network:
    name: redpanda_network
    driver: bridge

services:
  trade_producer:
    build:
      context: ../services/trade_producer
      dockerfile: Dockerfile
    environment:
      BROKER_ADDRESS: redpanda-0:9092
    networks:
      - redpanda_network

  trade_to_ohlc:
    build:
      context: ../services/trade_to_ohlc
      dockerfile: Dockerfile
    environment:
      BROKER_ADDRESS: redpanda-0:9092
    networks:
      - redpanda_network

  kafka_to_feature_store:
    build:
      context: ../services/kafka_to_feature_store
      dockerfile: Dockerfile
    environment:
      BROKER_ADDRESS: redpanda-0:9092
    networks:
      - redpanda_network